### PR TITLE
Ignore * keys for findUnused

### PR DESCRIPTION
**Pull request by Kerumen**
Fix a part of https://github.com/oliviertassinari/i18n-extract/issues/44

The ternary resolution should come in another PR.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@Kerumen It's a great first pull request on the project 👌🏻. Thank you for giving it a shot!

**Comment by Kerumen** [comment]
@oliviertassinari Thanks! 🙌 

Can you release as `0.6.1` please?

**Comment by oliviertassinari** [comment]
@Kerumen Sure, I'm on it!

**Comment by rpellerin** [comment]
This PR introduces a substantial regression, in that it reports many unused keys which are actually being used.

```javascript
const Yolo = ({ foo }) => <div>{i18n.t(foo, { scope: 'foo.bar' })}</div>
```

All keys that match `foo.bar.*` are reported as unused.

**Comment by oliviertassinari** [comment]
@rpellerin I might be wrong, but at first sight, your comment is exactly what motivated this change.
Going back to your code example. This plugin doesn't know any scope feature. Its considering it's a `*`. The `findUnused` method is closd useless in the Doctolib codebase. The change is only surfacing this core issue.

**Comment by rpellerin** [comment]
Should I expect it to handle such cases in the near future?

**Comment by oliviertassinari** [comment]
https://github.com/oliviertassinari/i18n-extract/issues/46

**Comment by rpellerin** [comment]
Amazing, thanks!

**Pull request merged**
