### PR TITLE
Get code fragment with keys

### LINKED ISSUE #31: Get code fragments with keys
Hi,

It does not seem to be possible to get code fragments from which the keys were matched. I use `extractFromFiles` to extract i18n keys from my code and check whether all my translations are actually used and so on.

However, as I added it on a previous code base, I have a lot of jokers returned. Typically, when I pass a variable to my translator, I get a `*` joker in the output keys from `i18n-extract`.

I am trying to rewrite my code to narrow down these jokers, but it is quite painful to find where it comes from in the code. It would be a really great addition to return, besides the matched keys, the file where it is coming from and the code fragment which gave the match. I think all this info is already available to `i18n-extract`, so I may have missed something to get it from the library. :/

Thanks!

EDIT: This would be especially useful since `forbidDynamic` could give extra information on the code fragments to fix :)

### PR DESCRIPTION
**Pull request by Phyks**
Update `extractCode` function to output the location of the extracted
keys as well as the translation keys.

This would close #31.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Have you tried running the following script https://github.com/oliviertassinari/i18n-extract/blob/master/examples/polyglot.js? Otherwise, that looks good 👍 .

**Comment by Phyks** [comment]
Yes, it is running fine on my codebase.

**Comment by Phyks** [comment]
Actually, it would be better if `findUnused` and such method was returning the complete key object, with the location. I will update the PR.

**Comment by Phyks** [comment]
Should be done :)

**Comment by oliviertassinari** [comment]
@Phyks Thanks!!

**Comment by Phyks** [comment]
Awesome, thanks for the new release!

**Pull request merged**
