### PR TITLE
Add support for ternary operator and logical expressions

### LINKED ISSUE #39: Unsupported node: ConditionalExpression & LogicalExpression
There isn't support for instances of:
* `extractFromCode("i18n(cond && 'im conditional')")`
* `extractFromCode("i18n(cat ? 'cat' : 'not cat')")`

[getKey](https://github.com/oliviertassinari/i18n-extract/blob/master/src/extractFromCode.js#L6) should at least return `'*'`

### PR DESCRIPTION
**Pull request by gsouf**
Hi,

This fix makes the ``getKey`` to be replaced with ``getKeys`` that is now able to return multiple keys at once. That way we can add support for logical expressions and ternary operators that required the ability to return multiple keys.

Fix #39

### CODE REVIEW

**Comment by gsouf** [comment]
Closing as maintainer dont plan to get this fixed.

**Comment by gsouf** [comment]
@oliviertassinari concerning travis failing for some reasons the eslints does not run the same way on my computer and on travis, getting it fixed to match travis way

**Comment by oliviertassinari** [comment]
@gsouf Thanks

**Comment by gsouf** [comment]
Thank you!

**Pull request merged**
